server:
  port: 9411

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    br.com.dataeasy: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zipkinsvr