zuul.ignored-services: "*"
zuul.prefix:  /api
zuul.routes.organizationservice: /organization/**
zuul.routes.licensingservice: /licensing/**
zuul.routes.authenticationservice: /auth/**
#zuul.routes.licensestatic.path: /licensestatic/**
#zuul.routes.licensestatic.url:  http://licenseservice-static:8081
#zuul.routes.licensestatic.serviceId: licensestatic
#zuul.routes.licensestatic.ribbon.listOfServers: http://licenseservice-static1:8081, http://licenseservice-static2:8082
#ribbon.eureka.enabled: false
zuul.sensitiveHeaders: Cookie,Set-Cookie
zuul.debug.request: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2500
#hystrix.command.licensingservice.execution.isolation.thread.timeoutInMilliseconds: 2
#licensingservice.ribbon.ReadTimeout: 2
signing.key: "345345fsdfsf5345"

logging.level.com.netflix: WARN
logging.level.org.springframework.web: WARN
logging.level.br.com.dataeasy: DEBUG

eureka.instance.preferIpAddress: true
eureka.client.registerWithEureka: true
eureka.client.fetchRegistry: true
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring.zipkin.baseUrl: http://localhost:9411

server.port: 8080